### ISSUE TITLE
There are some issues with the latest version

### ISSUE THREAD

**Issue by tailetan** [bfh/moodle-tiny_multilang2#6] opened 2023-09-12 08:01 UTC
Hi @srobotta, @lucaboesch ,
After testing the latest code, we found several issues as follows. Could you please take a look at them?
**Issue 1: There is an extra div when change or delete language tag**
**Steps to reproduce:**
- Select a text, then choose a language in multilang2 plugin.
- Click one of the 2 mlang tags to change another language.
- Navigate to View > Sourcecode.
- Observe the sourcecode. There is an extra div (EX: `<div id="sel-mce_0" class="mce-offscreen-selection" style="top: 7.31534px;" data-mce-bogus="all">&nbsp;<span class="multilang-begin mceNonEditable fallback" lang="zh" xml:lang="zh">{mlang zh}</span>&nbsp;</div>`)
-  The issue occurs the same when delete a mlang tag then view sourcecode
Please refer to the following attachment.
https://drive.google.com/file/d/1LKWz25Q_YOejLSKXAfHZFDPIalFp6b60/view?usp=sharing

**Issue 2: Multilang feature is not working if we select multiple lines/paragraphs** 
**Steps to reproduce:**
- Given there are several paragraphs.
- Select all/Ctrl+A paragrphs, then choose a language.
- Observe the {mlang} tag is on the top and bottom of the content.
- Navigate to View > Sourcecode. 
- Observe those {mlang} tag are wrapped by `<p>` tag
- Back to editor and observe the issue
Please refer to the following attachment.
https://drive.google.com/file/d/1Ub5YQNaD18YlnO4Q-sdjJbJmYbiqm-GC/view?usp=sharing
I think that if we select a language for several paragraphs, we should have a loop to iterate through them and then wrap each paragraph with a 'mlang' tag. What do you think about that?

Could you have a look at these issues and consider fix it ASAP?
Please let me know if you have any concerns. Thank you.

**Comment by srobotta** [comment] 2023-09-12 19:56
Hi Tai,

thank you for your comments and the screen casts.

Issue1: this seems to be a problem (e.g. with the disussion form) when a draft is reloaded. In this case when the editor is initialized, the content value is empty, hence nothing to style. Later the content is set (I haven't figured out yet how) then content is set but the onInit method (for the styling) is not called. Even though there is a language span tag, the styling is not applied. This leads to the error that you reapply some language and an additional span tag is added. I have no clue yet how to resolve this.

Issue2: There is a problem when selecting multiple block elements. I assume this works well with the multilang2 filter installed, however without this changes seem not feasible. This is because seleting the text once, I could add the language tags inside the content of each block element. However for applying another language, this doesn't work anymore. Therefore I tend to display an alert message when multiple paragraphs are selected and a language should be applied to. What do you think?

**Comment by tailetan** [comment] 2023-09-13 02:24
Just to provide more information about issue 1, I have reverted to my last commit, and the issue did not occur. It seems that your latest change has caused this issue. Could you please check it, Stephan?
Regarding issue 2, what do you think of my suggestion in the previous comment? If it's impossible, displaying an alert message is a good idea to prevent user confusion. Thanks.

**Comment by srobotta** [comment] 2023-09-13 07:07
First some prerequisites:
- tag higlighting must be enabled
- mutlilang2 filter must be disabled
- fallback span tag support must be enabled

At first I was not able to reproduce the error. However it's still there. Steps to reproduce:
- start a new discussion item, type some text, select it and add a language to it.
- Leave that for a while (or so that the autosave/whatever) takes that input.
- Without saving, reload the page. That loads the forum again without showing the editor. In the background however your latest input is restored.
- When you click the add new topic button, the editor should show up with the content that you have inserted before.
Expected outout: you see the language tags highlighting. What actually happens is that the unmodified content is shown.

I went back to b58dfa48639721cd6833884e85b500389b43a603 (before all your changes) and the problem behaves even more weird (when I try to save, suddenly the session content from yesterdays evening is placed into the editor). What I did find out is the autosave plugin that is interfering here. From what I have debugged, I believe the error was there before.

**Comment by srobotta** [comment] 2023-09-13 11:32
hi @tailetan 

the lastet version in master should contain fixes to both issues. Can you please check that on your side and give me feedback? I would like to await your response before creating a new release.

Thank you again for your testing, bugreports and the support.

**Comment by tailetan** [comment] 2023-09-13 12:27
Great news, Stephan. We will test your update and get back to you ASAP. Thanks

**Comment by tailetan** [comment] 2023-09-18 10:44
Hi @srobotta,

Our tester has completed testing 2 above issues. Currently, Issue 2 is working well, but Issue 1 still occurs in cases with the following step-by-step instructions, which I have updated in the description as below:
All evidences are attached in this: [Evidences](https://drive.google.com/drive/folders/16Y7ip-k0raiIAVnXrQ813kVfdnma326S?usp=sharing)

**1: Change front mlang tag**

1. Type some text in editor
2. Highlight text, 
3. Choose a language
4. Click on the front mlang tag
5. Change to another language
6. Click 'View' > 'Sourcecode' & observe
7. Click on 'X' button to close source code popup

**Actual outcome:** A `<div>` is displayed in the source code view. When I close the source code popup, the mlang tag disappears.

**Expected outcome:** No extra `<div>` is displayed in the source code view.

**2: Change back mlang tag**

1. Type some text in editor
2. Highlight text, 
3. Choose a language
4. Click on back mlang tag
5. Change to another language
6. Click 'View' > 'Sourcecode' & observe

**Actual outcome:** A `<div>` is displayed in the source code view. 

**Expected outcome:** No extra `<div>` is displayed in the source code view.

**3: Delete mlang tag**

1. Type some text in editor
2. Highlight text, 
3. Choose a language
4. Click one of the 2 mlang tags displaying within text field
5. Press 'Delete' key or 'Recycle bin' icon
6. Click 'View' > 'Sourcecode' & observe

**Actual outcome:** A `<div>` is displayed in the source code view. 

**Expected outcome:** No extra `<div>` is displayed in the source code view.

Could you have a look on this?
Please let me know if you have any concerns. Thank you.

**Comment by srobotta** [comment] 2023-09-22 10:48
Hi @tailetan 

Unfortunately I cannot reproduce the error. I also remember that I was able to reproduce this before (and figured out the reason) but cannot do so at the moment. I tried both Chrome and Firefox. If you are using Edge then I must postpone this for at least two weeks because I have no access to a Windows machine at the moment.
Can you please make sure that the last commit that you are seeing is  97cfb988b59602be83a676a98e6e7dc515421662 i.e. that you have the last version installed?

Thank you.

**Comment by tailetan** [comment] 2023-09-22 11:18
Hi @srobotta, Yes, I pulled the latest version, Stephan. However, I also tried all browsers (Edge, Chrome, and Firefox), but the issue still occurs.

**Comment by srobotta** [comment] 2023-09-22 11:36
Can you give me please more information about your setup, e.g. which settings for the tiny multilang plugin, which filters/plugins are installed, Especially which other Tiny plugins do you have.

**Comment by tailetan** [comment] 2023-09-22 14:18
Yes, I've configured the plugin as shown in the screenshot below. Please note that I've tried enabling/disabling and combining these settings, but the issue still persists. I haven't installed any filters or other plugins either. 

![image](https://github.com/bfh/moodle-tiny_multilang2/assets/55305972/3bc33d1c-38a6-4eaa-b5c2-4b0032615099)

Furthermore, I attempted to install the multilang to the Moodle core source, but unfortunately, the issue still persists with all browsers.
![image](https://github.com/bfh/moodle-tiny_multilang2/assets/55305972/428a9be0-5abb-4065-9c7f-1177b121cfa9)

**Comment by srobotta** [comment] 2023-09-26 16:34
Hi @tailetan,

Thank you for your patience. The problem was that I am developing in 4.3dev where the leftover div apparently didn't appear. Only 4.1 and 4.2 are affected. I was finally being able to reproduce it and could fix it.
Also I did a few adjustments:

- removing the setting fallbackspan: this should enable or disable whether the normal Moodle `<span class="multilang">` tags are supported. This was handled a bit inconsistend. Now these span tags will be supported always whenever the multilang2 filter is not installed.
- the separate language tag for the settings item has been replaced, now the plugin name is used (having an item that includes the name setting inside the plugin settings is a bit redundant). This had the effect that I had to adapt some behat tests as well.

Could you please ask your tester to verify that the bug has been fixed? Then I would create a new release.
I will close the issue once I have positive feedback from you.

Thank you again for your support and contributions.

**Comment by tailetan** [comment] 2023-10-05 09:59
Hi @srobotta, 
Apologies for the delayed response. Our tester has just verified the issue, and fortunately, it no longer occurs. The plugin now works as expected. Thank you very much for fixing the bug, Stephan. You can now close the issue and create a new release.

**Comment by srobotta** [comment] 2023-10-09 09:03
Thank you @tailetan for the confirmation. I am happy to hear that it works and that my effort was successful. I will create a new release now.

**Closed as completed by srobotta** 2023-10-09 09:03 UTC
